modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="lc_claim_economy"
version="3.8.0"
displayName="Lightman's Currency: Claim Economy"
authors="malik"
description='''Connects Lightman's Currency with FTB Chunks + FTB Teams, or Open Parties and Claims, for paid claims, upkeep, and protection management.'''

[[dependencies.lc_claim_economy]]
modId="neoforge"
type="required"
versionRange="[21.1.234,)"
ordering="NONE"
side="BOTH"

[[dependencies.lc_claim_economy]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.lc_claim_economy]]
modId="ftblibrary"
type="optional"
versionRange="[2101.1.32,)"
ordering="NONE"
side="BOTH"

[[dependencies.lc_claim_economy]]
modId="ftbteams"
type="optional"
versionRange="[2101.1.10,)"
ordering="NONE"
side="BOTH"

[[dependencies.lc_claim_economy]]
modId="ftbchunks"
type="optional"
versionRange="[2101.1.20,)"
ordering="NONE"
side="BOTH"

[[dependencies.lc_claim_economy]]
modId="openpartiesandclaims"
type="optional"
versionRange="[0.27.5,)"
ordering="NONE"
side="BOTH"

[[dependencies.lc_claim_economy]]
modId="lightmanscurrency"
type="required"
versionRange="[1.21-2.3.0.5,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="lc_claim_economy.mixins.json"
